# Generated by Django 5.0 on 2023-12-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthDay', models.DateTimeField(verbose_name="person's birthday")),
                ('relationship', models.CharField(max_length=200)),
            ],
        ),
    ]
