# Generated by Django 5.0 on 2023-12-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthDay',
            field=models.DateField(verbose_name="person's birthday"),
        ),
    ]
